project:
  type: website
  output-dir: _site

website:
  title: "Kyuri Park"
  site-url: "https://your-github-username.github.io/your-repository-name"
  description: "Personal academic website for Kyuri Park, PhD candidate."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: teaching.qmd
        text: Teaching
      - href: CV_KP_2605.pdf
        text: CV
    right:
      - icon: github
        href: https://github.com/your-github-username
      - icon: envelope
        href: mailto:your.email@example.com
  page-footer:
    center: "(c) 2026 Kyuri Park"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

execute:
  freeze: auto
