project:
  type: website
  output-dir: _site
  resources:
    - google2f202f7faba87218.html

website:
  title: "Kyuri Park"
  site-url: "https://kyuriparkecon.github.io"
  description: "Personal academic website for Kyuri Park, PhD candidate."
  navbar:
    search: false
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full

execute:
  freeze: auto
